"""Generate grayscale ICC profiles + C header from the nvIccAdvancedColorIdentity.icm template.

Patches:
- MHC2 color matrix -> grayscale coefficients (linear-space luminance mix)
- rTRC/gTRC/bTRC -> standard sRGB decoding curve (1024-pt 'curv')
- rXYZ/gXYZ/bXYZ -> sRGB primaries (D50 adapted)
- wtpt -> D50

Usage: python gen_icc.py <nvIccAdvancedColorIdentity.icm path>
Outputs: luma.icc / oklch.icc (binary) and icc_data.h (C arrays for embedding).
"""
import struct
import sys
import os

D50 = (0.9642, 1.0, 0.8249)
MAX_LUMINANCE = 250.0  # cd/m² assumed for the display

# sRGB D50 RGB<->XYZ (Bruce Lindbloom) — the pipeline wraps our matrix as
# [XYZtoRGB]·M·[RGBtoXYZ], i.e. M acts in XYZ space. To get a luminance mix
# in linear RGB space, the matrix rows must be w·XYZtoRGB.
SRGB_RGB2XYZ = ((0.4360747, 0.3850649, 0.1430804),
                (0.2225045, 0.7168786, 0.0606169),
                (0.0139322, 0.0971045, 0.7149281))
SRGB_XYZ2RGB = ((3.1338561, -1.6168667, -0.4906146),
                (-0.9787684, 1.9161415, 0.0334540),
                (0.0719453, -0.2289914, 1.4052427))

def to_xyz_space(w):
    """Return the XYZ-space matrix row equivalent to linear-RGB luminance mix w."""
    return [sum(w[i] * SRGB_XYZ2RGB[i][j] for i in range(3)) for j in range(3)]

SRGB_PRIMARIES = {
    b'rXYZ': (0.4360747, 0.2225045, 0.0139322),
    b'gXYZ': (0.3850649, 0.7168786, 0.0971045),
    b'bXYZ': (0.1430804, 0.0606169, 0.7149281),
}

def s15f16(v):
    return int(round(v * 65536))

def srgb_to_linear(x):
    return x / 12.92 if x <= 0.04045 else ((x + 0.055) / 1.055) ** 2.4

def find_tag(data, sig):
    ntags = struct.unpack('>I', data[128:132])[0]
    for i in range(ntags):
        off = 132 + i * 12
        if data[off:off + 4] == sig:
            return struct.unpack('>II', data[off + 4:off + 12])
    return None

def patch_matrix(data, w):
    o, s = find_tag(data, b'MHC2')
    assert o is not None
    moff = struct.unpack('>I', data[o + 20:o + 24])[0]
    b = bytearray(data)
    pos = o + moff
    # Matrix rows act in XYZ space per the fixed pipeline; convert the
    # linear-RGB luminance mix to its XYZ-space equivalent.
    vals = to_xyz_space(w) + [0.0]
    vals = vals * 3
    for v in vals:
        struct.pack_into('>i', b, pos, s15f16(v))
        pos += 4
    return bytes(b)

def patch_trc(data, sig, n=1024):
    """Overwrite a 'curv' TRC with the sRGB decoding curve (same byte layout)."""
    o, s = find_tag(data, sig)
    assert o is not None
    b = bytearray(data)
    pos = o + 12  # sig(4) + reserved(4) + count(4)
    for i in range(n):
        x = i / (n - 1)
        lin = srgb_to_linear(x)
        enc = min(65535, int(round(lin * 65536)))
        struct.pack_into('>H', b, pos, enc)
        pos += 2
    return bytes(b)

def patch_xyz(data, sig, xyz):
    """Overwrite an XYZType tag (4-byte 'XYZ ' signature + 12-byte XYZ)."""
    o, s = find_tag(data, sig)
    assert o is not None
    assert data[o:o + 4] == b'XYZ ', f'{sig} not XYZType: {data[o:o + 4]!r}'
    b = bytearray(data)
    for j, v in enumerate(xyz):
        struct.pack_into('>i', b, o + 4 + 4 * j, s15f16(v))
    return bytes(b)

def patch_lumi(data):
    """lumi tag = absolute XYZ of max luminance (wtpt * MAX_LUMINANCE/100)."""
    return patch_xyz(data, b'lumi',
                     tuple(v * MAX_LUMINANCE / 100.0 for v in D50))

def patch_mhc2_luminance(data):
    """Fix MHC2 min/max luminance fields (template carries odd values)."""
    o, s = find_tag(data, b'MHC2')
    assert o is not None
    b = bytearray(data)
    struct.pack_into('>i', b, o + 12, s15f16(0.0))          # min luminance
    struct.pack_into('>i', b, o + 16, s15f16(MAX_LUMINANCE))  # max luminance
    return bytes(b)

def to_c_array(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + ",".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)

def main():
    src = sys.argv[1]
    outdir = os.path.dirname(os.path.abspath(__file__))
    luma = (0.2126, 0.7152, 0.0722)
    oklch = (0.26788553, 0.68828797, 0.0438265)
    base = open(src, 'rb').read()
    files = {}
    for name, w in [('luma', luma), ('oklch', oklch)]:
        data = patch_matrix(base, w)
        for sig in (b'rTRC', b'gTRC', b'bTRC'):
            data = patch_trc(data, sig)
        for sig, xyz in SRGB_PRIMARIES.items():
            data = patch_xyz(data, sig, xyz)
        data = patch_xyz(data, b'wtpt', D50)
        data = patch_lumi(data)
        data = patch_mhc2_luminance(data)
        with open(os.path.join(outdir, f'{name}.icc'), 'wb') as f:
            f.write(data)
        files[name] = data
        print(f"{name}.icc: {len(data)} bytes")
    header = "// Auto-generated by gen_icc.py — do not edit.\n"
    header += "// Grayscale ICC profiles (template: nvIccAdvancedColorIdentity.icm, MIT/BSD licensed).\n"
    header += "#pragma once\n\n"
    header += to_c_array("g_luma_icc", files['luma']) + "\n\n"
    header += to_c_array("g_oklch_icc", files['oklch']) + "\n\n"
    header += "static const int g_luma_icc_len = sizeof(g_luma_icc);\n"
    header += "static const int g_oklch_icc_len = sizeof(g_oklch_icc);\n"
    with open(os.path.join(outdir, 'icc_data.h'), 'w', encoding='utf-8') as f:
        f.write(header)
    print("icc_data.h written")

if __name__ == '__main__':
    main()
