// mhc2_filter.exe — full-desktop grayscale via MHC2 ICC display profile
//
// Applies a color matrix at the kernel/scanout level (the same pipeline
// Windows' built-in color filter uses), so there is NO capture, NO overlay
// window, and ~zero per-frame cost.
//
// Control file: %SYSTEMROOT%\Temp\mhc2_filter_mode.txt   (0=off, 1=luma, 2=oklch)
// State  file: %SYSTEMROOT%\Temp\mhc2_filter_state.txt  (monitorDevicePath|origProfile per line)
// Log    file: %SYSTEMROOT%\Temp\mhc2_filter.log
// ICC files : %LOCALAPPDATA%\Colorink\mhc2\{luma,oklch}.icc
//
// Requirements: Windows 10 2004+ and a GPU that supports the color-space
// transform DDI (Intel 10th gen iGPU+ / AMD RX 500+ / NVIDIA GTX 10xx+).
//
// Build: run build.bat

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <setupapi.h>
#include <devguid.h>
#include <cstdio>
#include <cstring>
#include <cmath>
#include <cwchar>
#include <string>
#include <vector>

#pragma comment(lib, "setupapi.lib")

// ---- mscms.dll dynamic loading (avoid SDK header dependencies) -----------

typedef enum WCS_PROFILE_MANAGEMENT_SCOPE {
    WCS_PROFILE_MANAGEMENT_SCOPE_SYSTEM_WIDE = 0,
    WCS_PROFILE_MANAGEMENT_SCOPE_CURRENT_USER = 1
} WCS_PROFILE_MANAGEMENT_SCOPE;

typedef enum COLORPROFILETYPE {
    CPT_ICC = 0, CPT_DMP = 1, CPT_CAMP = 2, CPT_GMMP = 3
} COLORPROFILETYPE;

typedef enum COLORPROFILESUBTYPE {
    CPST_PERCEPTUAL = 0, CPST_RELATIVE_COLORIMETRIC = 1, CPST_SATURATION = 2,
    CPST_ABSOLUTE_COLORIMETRIC = 3, CPST_NONE = 4, CPST_RGB_WORKING_SPACE = 5,
    CPST_CUSTOM_WORKING_SPACE = 6, CPST_STANDARD_DISPLAY_COLOR_MODE = 7,
    CPST_EXTENDED_DISPLAY_COLOR_MODE = 8
} COLORPROFILESUBTYPE;

// Real mscms signatures (Win10 2004+). Displays are addressed by
// (targetAdapterID LUID, sourceID) from QueryDisplayConfig.
typedef HRESULT(WINAPI* FnInstallColorProfileW)(HANDLE hMachine, LPCWSTR pProfileName);
typedef HRESULT(WINAPI* FnUninstallColorProfileW)(HANDLE hMachine, LPCWSTR pProfileName, BOOL bDelete);
typedef HRESULT(WINAPI* FnColorProfileGetDisplayDefault)(
    WCS_PROFILE_MANAGEMENT_SCOPE scope, LUID targetAdapterID, UINT32 sourceID,
    COLORPROFILETYPE profileType, COLORPROFILESUBTYPE profileSubType, LPWSTR* profileNamePtr);
typedef HRESULT(WINAPI* FnColorProfileSetDisplayDefaultAssociation)(
    WCS_PROFILE_MANAGEMENT_SCOPE scope, PCWSTR profileName,
    COLORPROFILETYPE profileType, COLORPROFILESUBTYPE profileSubType,
    LUID targetAdapterID, UINT32 sourceID);

typedef HRESULT(WINAPI* FnColorProfileAddDisplayAssociation)(
    WCS_PROFILE_MANAGEMENT_SCOPE scope, PCWSTR profileName, LUID targetAdapterID, UINT32 sourceID,
    BOOL setAsDefault, BOOL associateAsAdvancedColor);
typedef BOOL(WINAPI* FnWcsSetUsePerUserProfiles)(PCWSTR pDeviceName, DWORD dwDeviceClass, BOOL usePerUserProfiles);
typedef BOOL(WINAPI* FnWcsGetUsePerUserProfiles)(PCWSTR pDeviceName, DWORD dwDeviceClass, BOOL* usePerUserProfiles);

static FnInstallColorProfileW                  pInstallColorProfileW;
static FnUninstallColorProfileW                pUninstallColorProfileW;
static FnColorProfileGetDisplayDefault        pColorProfileGetDisplayDefault;
static FnColorProfileSetDisplayDefaultAssociation pColorProfileSetDisplayDefaultAssociation;
static FnColorProfileAddDisplayAssociation    pColorProfileAddDisplayAssociation;
static FnWcsSetUsePerUserProfiles             pWcsSetUsePerUserProfiles;
static FnWcsGetUsePerUserProfiles             pWcsGetUsePerUserProfiles;

#define CLASS_MONITOR 0x6D6E7472  // 'mntr'

static std::wstring g_sysTemp;       // %SYSTEMROOT%\Temp
static std::wstring g_iccDir;        // %LOCALAPPDATA%\Colorink\mhc2
static std::wstring g_iccPath[2];    // 0=luma.icc  1=oklch.icc
static const wchar_t* g_iccName[2] = { L"luma.icc", L"oklch.icc" };

static void Log(const wchar_t* msg) {
    std::wstring p = g_sysTemp + L"\\mhc2_filter.log";
    HANDLE h = CreateFileW(p.c_str(), FILE_APPEND_DATA, FILE_SHARE_READ | FILE_SHARE_WRITE,
                           nullptr, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (h == INVALID_HANDLE_VALUE) return;
    SYSTEMTIME st; GetLocalTime(&st);
    wchar_t buf[1024];
    int n = swprintf(buf, 1024, L"[%02d:%02d:%02d.%03d] %s\r\n", st.wHour, st.wMinute, st.wSecond, st.wMilliseconds, msg);
    DWORD w; WriteFile(h, buf, n * sizeof(wchar_t), &w, nullptr);
    CloseHandle(h);
}

static std::wstring GetEnv(const wchar_t* name, const wchar_t* fallback) {
    DWORD n = GetEnvironmentVariableW(name, nullptr, 0);
    if (n == 0) return fallback ? fallback : L"";
    std::wstring v(n, L'\0');
    GetEnvironmentVariableW(name, &v[0], n);
    v.resize(n - 1);
    return v;
}

// ---- ICC profile data (embedded, generated by gen_icc.py) ---------------------
#include "icc_data.h"

static void CreateDirRecursive(const std::wstring& path) {
    std::wstring cur;
    for (size_t i = 0; i <= path.size(); i++) {
        if (i == path.size() || path[i] == L'\\') {
            if (cur.size() >= 3) CreateDirectoryW(cur.c_str(), nullptr); // skip "C:"
            if (i < path.size()) cur += path[i];
        } else {
            cur += path[i];
        }
    }
}

static bool WriteIccFile(const std::wstring& path, const unsigned char* data, size_t len) {
    HANDLE h = CreateFileW(path.c_str(), GENERIC_WRITE, 0, nullptr,
                           CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (h == INVALID_HANDLE_VALUE) return false;
    DWORD written = 0;
    BOOL ok = WriteFile(h, data, (DWORD)len, &written, nullptr);
    CloseHandle(h);
    return ok && written == len;
}

static bool EnsureIccFiles() {
    CreateDirRecursive(g_iccDir);
    bool ok = true;
    ok &= WriteIccFile(g_iccPath[0], g_luma_icc, sizeof(g_luma_icc));
    ok &= WriteIccFile(g_iccPath[1], g_oklch_icc, sizeof(g_oklch_icc));
    if (!ok) Log(L"FAILED to write ICC files");
    return ok;
}

// ---- display enumeration (QueryDisplayConfig) ----------------------------
// NOTE: structs must use NATURAL alignment — the Win32 headers rely on
// compiler padding (LUID is 8-byte aligned), e.g.
// DISPLAYCONFIG_PATH_SOURCE_INFO = 24 bytes, DISPLAYCONFIG_PATH_INFO = 80.

struct DC_SOURCE_INFO { LUID adapterId; UINT32 id; UINT32 modeInfoIdx; UINT32 statusFlags; };
struct DC_TARGET_INFO { LUID adapterId; UINT32 id; UINT32 modeInfoIdx; UINT32 outputTechnology;
                        UINT32 rotation; UINT32 scaling; UINT32 refreshNum; UINT32 refreshDen;
                        UINT32 scanLineOrdering; BOOL targetAvailable; UINT32 statusFlags; };
struct DC_PATH_INFO { DC_SOURCE_INFO sourceInfo; DC_TARGET_INFO targetInfo; UINT32 flags; };

struct DC_DEVICE_INFO_HEADER { UINT32 type; UINT32 size; LUID adapterId; UINT32 id; };
struct DC_TARGET_DEVICE_NAME {
    DC_DEVICE_INFO_HEADER header;
    UINT32 flags;
    UINT32 outputTechnology;
    UINT16 edidManufactureId;
    UINT16 edidProductCodeId;
    UINT32 connectorInstance;
    wchar_t monitorFriendlyDeviceName[64];
    wchar_t monitorDevicePath[128];
};

typedef LONG(WINAPI* FnGetDisplayConfigBufferSizes)(UINT32 flags, UINT32* numPathArrayElements, UINT32* numModeInfoArrayElements);
typedef LONG(WINAPI* FnQueryDisplayConfig)(UINT32 flags, UINT32* numPathArrayElements, DC_PATH_INFO* pathArray,
                                           UINT32* numModeInfoArrayElements, void* modeInfoArray, UINT32* currentTopologyId);
typedef LONG(WINAPI* FnDisplayConfigGetDeviceInfo)(DC_DEVICE_INFO_HEADER* requestPacket);

static FnGetDisplayConfigBufferSizes pGetDisplayConfigBufferSizes;
static FnQueryDisplayConfig pQueryDisplayConfig;
static FnDisplayConfigGetDeviceInfo pDisplayConfigGetDeviceInfo;

#define MHC2_QDC_ONLY_ACTIVE_PATHS 0x2
#define MHC2_QDC_DATABASE_CURRENT 0x4
#define DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME 2

struct DisplayInfo {
    std::wstring devicePath;    // e.g. \\?\DISPLAY#TMX1601#...
    LUID adapterId;
    UINT32 sourceId;
};

static bool InitDisplayConfig() {
    HMODULE u32 = LoadLibraryW(L"user32.dll");
    if (!u32) return false;
    pGetDisplayConfigBufferSizes = (FnGetDisplayConfigBufferSizes)GetProcAddress(u32, "GetDisplayConfigBufferSizes");
    pQueryDisplayConfig = (FnQueryDisplayConfig)GetProcAddress(u32, "QueryDisplayConfig");
    pDisplayConfigGetDeviceInfo = (FnDisplayConfigGetDeviceInfo)GetProcAddress(u32, "DisplayConfigGetDeviceInfo");
    return pGetDisplayConfigBufferSizes && pQueryDisplayConfig && pDisplayConfigGetDeviceInfo;
}

static std::vector<DisplayInfo> EnumerateDisplays() {
    std::vector<DisplayInfo> out;
    if (!pQueryDisplayConfig) return out;
    // QDC_ONLY_ACTIVE_PATHS fails on some machines (ERROR_INVALID_PARAMETER);
    // QDC_DATABASE_CURRENT returns the same current configuration.
    static const UINT32 kFlags[2] = { MHC2_QDC_ONLY_ACTIVE_PATHS, MHC2_QDC_DATABASE_CURRENT };
    std::vector<DC_PATH_INFO> paths;
    std::vector<BYTE> modes;
    for (UINT32 f : kFlags) {
        UINT32 pathCount = 0, modeCount = 0;
        if (pGetDisplayConfigBufferSizes(f, &pathCount, &modeCount) != 0) continue;
        paths.assign(pathCount, DC_PATH_INFO{});
        modes.assign(modeCount * 64, 0);
        UINT32 topology = 0;
        if (pQueryDisplayConfig(f, &pathCount, paths.data(), &modeCount, modes.data(), &topology) == 0) {
            paths.resize(pathCount);
            break;
        }
        paths.clear();
    }
    if (paths.empty()) {
        Log(L"QueryDisplayConfig failed for all flag sets");
        return out;
    }
    for (auto& p : paths) {
        DC_TARGET_DEVICE_NAME tname;
        memset(&tname, 0, sizeof(tname));
        tname.header.type = DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME;
        tname.header.size = sizeof(tname);
        tname.header.adapterId = p.targetInfo.adapterId;
        tname.header.id = p.targetInfo.id;
        if (pDisplayConfigGetDeviceInfo(&tname.header) != 0) continue;
        DisplayInfo di;
        di.devicePath = tname.monitorDevicePath;
        di.adapterId = p.sourceInfo.adapterId;
        di.sourceId = p.sourceInfo.id;
        out.push_back(di);
    }
    return out;
}

// Monitor driver keys (e.g. "{4d36e96e-...}\\0001") via SetupAPI. Needed to
// toggle per-user color profiles per display (WcsSetUsePerUserProfiles).
static std::vector<std::wstring> EnumerateMonitorDriverKeys() {
    std::vector<std::wstring> out;
    HDEVINFO devs = SetupDiGetClassDevsW(&GUID_DEVCLASS_MONITOR, nullptr, nullptr, DIGCF_PRESENT);
    if (devs == INVALID_HANDLE_VALUE) return out;
    for (DWORD i = 0; ; i++) {
        SP_DEVINFO_DATA did;
        memset(&did, 0, sizeof(did));
        did.cbSize = sizeof(did);
        if (!SetupDiEnumDeviceInfo(devs, i, &did)) break;
        DWORD type = 0, size = 0;
        if (!SetupDiGetDeviceRegistryPropertyW(devs, &did, SPDRP_DRIVER, &type, nullptr, 0, &size)
            && GetLastError() == ERROR_INSUFFICIENT_BUFFER) {
            std::wstring key(size / 2, L'\0');
            if (SetupDiGetDeviceRegistryPropertyW(devs, &did, SPDRP_DRIVER, &type,
                                                  (PBYTE)&key[0], size, &size))
                out.push_back(key.c_str());
        }
    }
    SetupDiDestroyDeviceInfoList(devs);
    return out;
}

static void SetPerUserProfiles(const std::vector<std::wstring>& driverKeys, BOOL enable) {
    if (!pWcsSetUsePerUserProfiles) {
        Log(L"SetPerUserProfiles: WcsSetUsePerUserProfiles unavailable");
        return;
    }
    wchar_t logBuf[256];
    swprintf(logBuf, 256, L"SetPerUserProfiles: %u monitor driver keys", (unsigned)driverKeys.size());
    Log(logBuf);
    static const wchar_t* kBase = L"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Class\\";
    for (auto& key : driverKeys) {
        std::wstring full = std::wstring(kBase) + key;
        BOOL ok = pWcsSetUsePerUserProfiles(full.c_str(), CLASS_MONITOR, enable);
        swprintf(logBuf, 256, L"  WcsSetUsePerUserProfiles(%s, %d) = %d", full.c_str(), enable ? 1 : 0, ok ? 1 : 0);
        Log(logBuf);
    }
}

// ---- profile application / restore ---------------------------------------

static std::wstring GetDefaultProfile(const DisplayInfo& disp) {
    if (!pColorProfileGetDisplayDefault) return L"";
    // Try SDR subtype first; HDR/Advanced-Color displays need the extended mode.
    for (int sub : { CPST_STANDARD_DISPLAY_COLOR_MODE, CPST_EXTENDED_DISPLAY_COLOR_MODE }) {
        LPWSTR namePtr = nullptr;
        HRESULT hr = pColorProfileGetDisplayDefault(
            WCS_PROFILE_MANAGEMENT_SCOPE_CURRENT_USER, disp.adapterId, disp.sourceId,
            CPT_ICC, (COLORPROFILESUBTYPE)sub, &namePtr);
        if (FAILED(hr)) continue;
        std::wstring name = namePtr ? namePtr : L"";
        if (namePtr) LocalFree(namePtr);
        return name;
    }
    return L"";
}

static bool SetDefaultProfile(const DisplayInfo& disp, const std::wstring& profileName) {
    if (!pColorProfileSetDisplayDefaultAssociation) return false;
    for (int sub : { CPST_STANDARD_DISPLAY_COLOR_MODE, CPST_EXTENDED_DISPLAY_COLOR_MODE }) {
        HRESULT hr = pColorProfileSetDisplayDefaultAssociation(
            WCS_PROFILE_MANAGEMENT_SCOPE_CURRENT_USER,
            profileName.empty() ? nullptr : profileName.c_str(),
            CPT_ICC, (COLORPROFILESUBTYPE)sub,
            disp.adapterId, disp.sourceId);
        if (SUCCEEDED(hr)) return true;
        wchar_t buf[256];
        swprintf(buf, 256, L"  SetDefault(sub=%d, hr=0x%08X) for srcId=%u", sub, (unsigned)hr, disp.sourceId);
        Log(buf);
    }
    return false;
}

static std::wstring ReadFileContent(const std::wstring& path) {
    HANDLE h = CreateFileW(path.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr,
                           OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (h == INVALID_HANDLE_VALUE) return L"";
    DWORD size = GetFileSize(h, nullptr);
    std::wstring s(size / 2, L'\0');
    DWORD read = 0;
    ReadFile(h, &s[0], size, &read, nullptr);
    CloseHandle(h);
    return s;
}

// Control files are single-byte ASCII ("0"/"1"/"2") — read as raw bytes.
static std::string ReadAsciiFile(const std::wstring& path) {
    HANDLE h = CreateFileW(path.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr,
                           OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (h == INVALID_HANDLE_VALUE) return "";
    DWORD size = GetFileSize(h, nullptr);
    std::string s(size, '\0');
    DWORD read = 0;
    ReadFile(h, &s[0], size, &read, nullptr);
    CloseHandle(h);
    return s;
}

static void WriteStateFile(const std::vector<std::pair<std::wstring, std::wstring>>& entries) {
    std::wstring path = g_sysTemp + L"\\mhc2_filter_state.txt";
    std::wstring content;
    for (auto& e : entries)
        content += e.first + L"|" + e.second + L"\r\n";
    HANDLE h = CreateFileW(path.c_str(), GENERIC_WRITE, 0, nullptr,
                           CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (h == INVALID_HANDLE_VALUE) return;
    DWORD w; WriteFile(h, content.c_str(), (DWORD)(content.size() * 2), &w, nullptr);
    CloseHandle(h);
}

static void ClearStateFile() { WriteStateFile({}); }

static std::vector<std::pair<std::wstring, std::wstring>> ReadStateFile() {
    std::vector<std::pair<std::wstring, std::wstring>> out;
    std::wstring content = ReadFileContent(g_sysTemp + L"\\mhc2_filter_state.txt");
    size_t pos = 0;
    while (pos < content.size()) {
        size_t nl = content.find(L'\n', pos);
        std::wstring line = content.substr(pos, nl == std::wstring::npos ? std::wstring::npos : nl - pos);
        pos = (nl == std::wstring::npos) ? content.size() : nl + 1;
        if (!line.empty() && line.back() == L'\r') line.pop_back();
        size_t sep = line.find(L'|');
        if (sep != std::wstring::npos)
            out.push_back({ line.substr(0, sep), line.substr(sep + 1) });
    }
    return out;
}

static int ReadMode() {
    std::string content = ReadAsciiFile(g_sysTemp + L"\\mhc2_filter_mode.txt");
    if (content.empty()) return 0;
    return (content[0] == '1' || content[0] == '2') ? (int)(content[0] - '0') : 0;
}

// Returns true if the filter was applied to all displays.
static bool ApplyFilter(int mode) {
    if (mode < 1 || mode > 2 || !pInstallColorProfileW || !pColorProfileSetDisplayDefaultAssociation) {
        Log(L"ApplyFilter: unavailable (mscms missing or bad mode)");
        return false;
    }
    std::vector<DisplayInfo> displays = EnumerateDisplays();
    if (displays.empty()) { Log(L"ApplyFilter: no displays found"); return false; }

    HRESULT hr = pInstallColorProfileW(nullptr, g_iccPath[mode - 1].c_str());
    if (FAILED(hr)) {
        wchar_t buf[256];
        swprintf(buf, 256, L"InstallColorProfile failed hr=0x%08X", (unsigned)hr);
        Log(buf);
        return false;
    }

    // ColorProfileSetDisplayDefaultAssociation with CURRENT_USER scope only
    // works on displays with per-user profiles enabled.
    std::vector<std::wstring> driverKeys = EnumerateMonitorDriverKeys();
    SetPerUserProfiles(driverKeys, TRUE);

    std::vector<std::pair<std::wstring, std::wstring>> state;
    wchar_t logBuf[512];
    bool allOk = true;
    for (auto& disp : displays) {
        std::wstring orig = GetDefaultProfile(disp);
        if (!SetDefaultProfile(disp, g_iccName[mode - 1])) {
            HRESULT hre = 0;
            swprintf(logBuf, 512, L"SetDisplayDefaultAssociation failed for %s (hr=0x%08X)", disp.devicePath.c_str(), (unsigned)hre);
            Log(logBuf);
            allOk = false;
            continue;
        }
        state.push_back({ disp.devicePath, orig });
        swprintf(logBuf, 512, L"Applied mode=%d to %s (orig=%s)", mode, disp.devicePath.c_str(),
                 orig.empty() ? L"<none>" : orig.c_str());
        Log(logBuf);
    }
    // Record successful associations even on partial failure, so Restore can
    // undo exactly what was applied (prevents residue on the working displays).
    if (!state.empty()) WriteStateFile(state);
    return allOk;
}

static void RestoreFilter() {
    if (!pColorProfileSetDisplayDefaultAssociation || !pUninstallColorProfileW) return;
    auto entries = ReadStateFile();
    std::vector<DisplayInfo> displays = EnumerateDisplays();
    wchar_t logBuf[512];
    // match state entries to current displays by device path
    for (auto& e : entries) {
        bool restored = false;
        for (auto& disp : displays) {
            if (disp.devicePath == e.first) {
                if (!e.second.empty()) {
                    restored = SetDefaultProfile(disp, e.second);
                    swprintf(logBuf, 512, restored ? L"Restored %s -> %s" : L"Restore FAILED %s -> %s",
                             e.first.c_str(), e.second.c_str());
                } else {
                    restored = SetDefaultProfile(disp, L"");
                    swprintf(logBuf, 512, restored ? L"Restored %s -> system default" : L"Restore(default) FAILED %s",
                             e.first.c_str());
                }
                Log(logBuf);
                break;
            }
        }
        if (!restored) {
            swprintf(logBuf, 512, L"Restore skipped (display gone): %s", e.first.c_str());
            Log(logBuf);
        }
    }
    pUninstallColorProfileW(nullptr, g_iccPath[0].c_str(), FALSE);
    pUninstallColorProfileW(nullptr, g_iccPath[1].c_str(), FALSE);
    ClearStateFile();
}

// Re-apply if Windows silently dropped the association (display events, etc.)
static void SelfHealIfNeeded(int mode) {
    if (mode < 1 || mode > 2) return;
    auto entries = ReadStateFile();
    if (entries.empty()) return;
    bool need = false;
    for (auto& disp : EnumerateDisplays()) {
        std::wstring cur = GetDefaultProfile(disp);
        if (cur != g_iccName[mode - 1]) { need = true; break; }
    }
    if (need) {
        Log(L"Association lost — re-applying");
        ApplyFilter(mode);
    }
}

// ---- main loop ------------------------------------------------------------

int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) {
    g_sysTemp = GetEnv(L"SYSTEMROOT", L"C:\\Windows") + L"\\Temp";
    std::wstring local = GetEnv(L"LOCALAPPDATA", L"");
    if (local.empty()) local = GetEnv(L"USERPROFILE", L"") + L"\\AppData\\Local";
    g_iccDir = local + L"\\Colorink\\mhc2";
    g_iccPath[0] = g_iccDir + L"\\luma.icc";
    g_iccPath[1] = g_iccDir + L"\\oklch.icc";

    HMODULE mscms = LoadLibraryW(L"mscms.dll");
    if (!mscms) { Log(L"mscms.dll not found"); return 1; }
    pInstallColorProfileW = (FnInstallColorProfileW)GetProcAddress(mscms, "InstallColorProfileW");
    pUninstallColorProfileW = (FnUninstallColorProfileW)GetProcAddress(mscms, "UninstallColorProfileW");
    pColorProfileGetDisplayDefault = (FnColorProfileGetDisplayDefault)GetProcAddress(mscms, "ColorProfileGetDisplayDefault");
    pColorProfileSetDisplayDefaultAssociation = (FnColorProfileSetDisplayDefaultAssociation)GetProcAddress(mscms, "ColorProfileSetDisplayDefaultAssociation");
    pColorProfileAddDisplayAssociation = (FnColorProfileAddDisplayAssociation)GetProcAddress(mscms, "ColorProfileAddDisplayAssociation");
    pWcsSetUsePerUserProfiles = (FnWcsSetUsePerUserProfiles)GetProcAddress(mscms, "WcsSetUsePerUserProfiles");
    pWcsGetUsePerUserProfiles = (FnWcsGetUsePerUserProfiles)GetProcAddress(mscms, "WcsGetUsePerUserProfiles");
    if (!pColorProfileSetDisplayDefaultAssociation || !pColorProfileGetDisplayDefault) {
        Log(L"ColorProfile* API not available (need Win10 2004+)");
        return 2;
    }
    if (!InitDisplayConfig()) { Log(L"QueryDisplayConfig unavailable"); return 3; }
    if (!EnsureIccFiles()) return 4;

    int mode = ReadMode();
    // Crash self-heal: state file exists but mode is off -> restore leftovers.
    if (mode == 0 && !ReadStateFile().empty()) {
        Log(L"Self-heal: restoring leftover state");
        RestoreFilter();
    }
    if (mode > 0) ApplyFilter(mode);   // (re)apply on startup
    Log(mode > 0 ? L"Startup: filter active" : L"Startup: idle");

    int lastMode = mode;
    DWORD lastHeal = GetTickCount();
    for (;;) {
        Sleep(200);
        int m = ReadMode();
        if (m != lastMode) {
            lastMode = m;
            if (m > 0) ApplyFilter(m);
            else       RestoreFilter();
        }
        // periodic self-heal (every 5 s while active)
        if (m > 0 && GetTickCount() - lastHeal > 5000) {
            lastHeal = GetTickCount();
            SelfHealIfNeeded(m);
        }
    }
    return 0;
}
